### ISSUE TITLE
Gnosis chain preset

### ISSUE THREAD

**Issue by cbermudez97** [pk910/dora#33]
I'm trying to start the explorer for a Devnet based on the [Gnosis Chain Preset](https://github.com/gnosischain/configs/tree/main/presets/gnosis). Currently, it fails with the following message:
```
time="2023-10-03T18:27:49Z" level=fatal msg="error reading config file: tried to use unknown chain-preset: gnosis"
```
Possible Solution:
- [x] Add Gnosis preset configuration to https://github.com/pk910/dora/tree/master/config. Perhaps including https://github.com/gobitfly/eth2-beaconchain-explorer/blob/master/config/gnosis.chain.yml

**Comment by pk910** [comment]
Cool thing :+1:  
Thanks for adding the configs.

Please share how it's working :)
I've never tried the explorer with a chain that does not use the usual 12s/32slots schedule.

**Comment by cbermudez97** [comment]
Thanks @pk910. Tried out a local docker image on the Devnet I mentioned and looks like it seems to be working well. Is there something else in particular that would be a good idea to try out?

**Comment by pk910** [comment]
Cool 👍
Nope,  actually, the explorer is not that big that there are hidden features or so.
If the startpage, epochs overview, epoch details, slot overview & slot details pages work, that's pretty much everything that is related to the slot schedule.
Thanks again for trying it :)  Great to know that the explorer works for custom slot schedules too :)
